### ISSUE TITLE
DynamoDb: Response from `Query` command does not `unmarshall` `LastEvaluatedKey`attribute

### ISSUE THREAD

**Issue by MartinRamm** [architect/aws-lite#114]
### Describe the issue

When running a `query` command that returns more than 100 Items, the responds contains a `LastEvaluatedKey` attribute to let you know that not all Items that match the query are returned.

When using `@architect/functions@7.0.0`, the value of `LastEvaluatedKey` is in the JSON format. When using `@architect/functions@8.0.4`, the value is in the DynamoDB JSON (marshalled JSON) format.

### Expected behavior

LastEvaluatedKey is in the JSON format

### Steps to reproduce

1. Run a query that returns more than 100 Items
2. The response contains a `LastEvaluatedKey` attribute, whose value is marshalled and needs to be unmarshalled by the library.

### How urgent do you feel this bug is?

P2

**Comment by ryanblock** [comment]
Hey @MartinRamm! I would consider the behavior that you are describing a bit of a regression (and covered under the breaking changes from 7-8). That data format is harder to reason about and symptomatic of the usability issues of the old SDK. (Related: when passing the pagination token in to lite it also does not need to be serialized to AWS flavored JSON!)

If you prefer the older way of working, Functions does still provide the ability to use the AWS SDK document client. Did you happen to see the new tables option?

```js 
let client = await arc.tables({ awsSdkClient: true })
client._db // AWS.DynamoDB
client._doc // AWS.DynamoDB.DocumentClient
```
