### ISSUE TITLE
Weird error from @aws-lite/client: SQS.SendMessage

### ISSUE THREAD

**Issue by frankleng** [architect/aws-lite#115]
### Describe the issue

```{
    "errorType": "TypeError",
    "errorMessage": "@aws-lite/client: SQS.SendMessage: Cannot read properties of undefined (reading 'x-amzn-requestid')",
    "service": "sqs",
    "property": "SQS",
    "time": "2024-03-23T08:01:47.140Z",
    "stack": [
        "TypeError: @aws-lite/client: SQS.SendMessage: Cannot read properties of undefined (reading 'x-amzn-requestid')",
        "    at Object.yB (/node_modules/.pnpm/@aws-lite+sqs@0.2.1/node_modules/@aws-lite/sqs/src/index.mjs:30:16)",
        "    at Object.SendMessage (/node_modules/.pnpm/@aws-lite+client@0.17.3/node_modules/@aws-lite/client/src/client-factory.js:160:47)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
}
```

### Expected behavior

in sqs/src/index.mjs - ln 33

```
  if (error && headers['x-amzn-requestid']) error.requestId = headers['x-amzn-requestid']
```
 
 I'm not sure why `headers` would be undefined, but seems like we should add an extra check so it doesn't crash

### Steps to reproduce

arc.queues.publish

### Platform / version

- Node version: 20.11
- Package manager version: pnpm 8.5

### How urgent do you feel this bug is?

P1

**Comment by filmaj** [comment]
In what context are you seeing this error? Locally in `arc sandbox` or deployed to a Lambda?

**Comment by frankleng** [comment]
> In what context are you seeing this error? Locally in `arc sandbox` or deployed to a Lambda?

deployed

**Comment by ryanblock** [comment]
That's fine, although I've never seen a case where an AWS API doesn't return headers (as in this case, where you get API metadata back); how did you produce this error state @frankleng?

**Comment by frankleng** [comment]
> That's fine, although I've never seen a case where an AWS API doesn't return headers (as in this case, where you get API metadata back); how did you produce this error state @frankleng?

this was from a scheduled lambda, calling `queues.publish` to fan out task to a work queue

**Comment by ryanblock** [comment]
`arc.queues.publish` and `calling queues.publish` are not usable steps to reproduce, are you able to assemble specific details I can use to reproduce this issue?

**Comment by filmaj** [comment]
Maybe it's in a lambda that's not invoked by an HTTP event? Scheduled trigger? Database stream? SNS or SQS?

**Comment by frankleng** [comment]
> `arc.queues.publish` and `calling queues.publish` are not usable steps to reproduce, are you able to assemble specific details I can use to reproduce this issue?

interesting. i've since reverted arc/func, will have to find time to try 8.0 again
unsure if related - we do set `groupID` in some of these `publish` calls

**Comment by ryanblock** [comment]
Haven't heard anything about this in a while, will close for now but let's reopen if it makes sense!
