### ISSUE TITLE
DynamoDB.Query: socket hang up

### ISSUE THREAD

**Issue by tkadlec** [architect/aws-lite#125]
### Describe the issue

Once deployed to AWS, I will get sporadic errors. Looking at the logs, I see something like this every time:

```
{
    "errorType": "Error",
    "errorMessage": "@aws-lite/client: DynamoDB.Query: socket hang up",
    "message": "@aws-lite/client: DynamoDB.Query: socket hang up",
    "service": "dynamodb",
    "property": "DynamoDB",
    "awsDoc": "https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html",
    "readme": "https://aws-lite.org/services/dynamodb#query",
    "rawStack": "Error: socket hang up\n    at connResetException (node:internal/errors:720:14)\n    at TLSSocket.socketCloseListener (node:_http_client:474:25)\n    at TLSSocket.emit (node:events:529:35)\n    at node:net:350:12\n    at TCP.done (node:_tls_wrap:657:7)",
    "host": "dynamodb.us-west-2.amazonaws.com",
    "protocol": "https",
    "time": "2024-05-07T17:24:28.784Z",
    "stack": [
        "Error: @aws-lite/client: DynamoDB.Query: socket hang up",
        "    at errorHandler (/var/task/node_modules/@aws-lite/client/src/error.js:13:46)",
        "    at Query (/var/task/node_modules/@aws-lite/client/src/client-factory.js:167:17)"
    ]
}
```

### Expected behavior

I would expect it not to error. :)

### Steps to reproduce

Ok, I know this is useless, but it's so sporadic I've been having zero success finding out how to reliably reproduce. It happens only occasionally, just enough to be annoying.

I'm posting this in the hopes that it's something simple or something others may have come across too.

### Platform / version

- Node version: (e.g. Node.js 20.5) nodejs18.x

### How urgent do you feel this bug is?

P2

**Comment by ryanblock** [comment]
@tkadlec all good, and (un)fortunately I have definitely seen this error! It doesn't reliably reproduce because it's (usually) a lower level API retry issue.

`aws-lite` v0.19.0 (2024-02-28) introduced retries (see https://github.com/architect/aws-lite/issues/106), which have resolved this error – so far, that I've seen, anyway. Can you confirm which version of `@aws-lite/client` you're using? (And `@aws-lite/dynamodb` if possible?)

**Comment by tkadlec** [comment]
Fun! :) 

Ok...this might be the issue then. Looking at what's installed....

```
├─┬ @begin/data@5.0.3
│ ├── @aws-lite/client@0.17.2
│ ├── @aws-lite/dynamodb@0.3.4
| ...
```

**Comment by ryanblock** [comment]
Ah, ok! Just bumped `@begin/data` to v5.0.4, which includes the latest `@aws-lite/client`, this should fix your issues. Thanks for reporting!

**Comment by tkadlec** [comment]
Awesome! Thanks @ryanblock!
