### ISSUE TITLE
Expose S3 User Defined Metadata

### ISSUE THREAD

**Issue by fedellen** [architect/aws-lite#146]
### Describe the problem underlying the enhancement request

aws-lite doesn't currently forward user defined s3 metadata from `z-amz-meta-*` down from header results. For our system, would be specifically useful on `HeadRequest` as we use this user defined metadata to determine `GetRequest` offsets

### Describe the solution you'd like (if any)

This user defined metadata should be available in the headers at `z-amz-meta-*`. I left a proposed solution at PR #145 -- but I'm not entirely convinced it would do the trick or is what you're looking for there

### Describe alternative solutions you've considered

We can currently head check the bucket directly to get this information as a workaround

**Comment by ryanblock** [comment]
Your solution should work ok, I think – will test and verify! Related, we should also allow writing metadata via `PutObject` and `Upload`, so I'll add that as well here: https://github.com/architect/aws-lite/pull/143

**Comment by ryanblock** [comment]
Added ability to append metadata here: https://github.com/architect/aws-lite/pull/143/commits/f03d7e6a8a567b478bb2db4321e4566aa7250507

We're aiming to merge this S3 release shortly, these changes should be shipped this week. Thanks @fedellen!
