### ISSUE TITLE
`removeUndefinedVariables` is not passed to AWS vendor'ed marshaller

### ISSUE THREAD

**Issue by andybee** [architect/aws-lite#147]
### Describe the issue

If you pass an item to the DynamoDB client where a property value is `undefined`, the following error is thrown:

> @aws-lite/client: DynamoDB.BatchWriteItem: Pass options.removeUndefinedValues=true to remove undefined values from map/array/set.

However, there appears to be nowhere documented to define this value. In the docs for `arc.tables()` an option is documented for `awsjsonMarshall`, which traces through to the aws-lite client constructor, but doesn't appear to have any affect.

### Expected behavior

Setting up `aws-lite` as follows:
```
import awsLite from '@aws-lite/client'

let aws = await awsLite({
  plugins: [ '@aws-lite/dynamodb' ],
  awsjsonMarshall: {
    removeUndefinedValues: true,
  },
});
```

would allow:
```
aws.DynamoDB.BatchWriteItem({
  RequestItems: {
    foo: [
      PutRequest: {
        Item: {
          PK: 1,
          foo: undefined,
        },
      },
    ],
  }
});
```

without throwing an error about undefined values.

### Steps to reproduce

1. Attempt to define `removeUndefinedValues` AWS JSON marshaller option on `aws-lite`
2. Attempt to put an item to DynamoDB with an undefined value with `aws-lite`

### Platform / version

- Node version: 20.14.0
- Package manager version: 10.7.0

### How urgent do you feel this bug is?

P2

**Comment by ryanblock** [comment]
Hmm, I tried testing your repro, unfortunately the code example was invalid (`foo: [  PutRequest: { ...`). However, here's where we test and validate the effects of setting `config.awsjsonMarhshall.removeUndefinedValues`:
- Disabled: https://github.com/architect/aws-lite/blob/00969954f81eb14194b1a07b2db84fda13805968/test/unit/src/index-config-test.mjs#L127-L152
- Enabled: https://github.com/architect/aws-lite/blob/00969954f81eb14194b1a07b2db84fda13805968/test/unit/src/index-config-test.mjs#L175-L222
Anything jump out to you here?

**Comment by andybee** [comment]
Ah, that's embarrassing. Perhaps it's an issue with @architect/functions table wrapper? I've created a quick repo here:
https://github.com/andybee/arc-ddb-issue

If you hit the `/` handler it should trigger the error.

**Comment by ryanblock** [comment]
Thanks for the repro repo, perfect! I was able to track down the issue. Due to certain DynamoDB methods' deep nesting, we manually (for lack of a better term) handle (un)marshalling in certain cases (e.g. https://github.com/architect/aws-lite/blob/00969954f81eb14194b1a07b2db84fda13805968/plugins/dynamodb/src/index.mjs#L178-L181). As you can see there, we're just using the raw (un)marshalling methods without passing additional config. So this is specifically a `@aws-lite/dynamodb` bug, which I'll get to patching asap – should be by eod!

**Comment by andybee** [comment]
Aha! I was in a bit of a rush when first reporting this so hopped around the codebase quite a bit and didn't spot those calls.

Thanks for your time investigating and look forward to the forthcoming update.
