### ISSUE TITLE
First set of plugins

### ISSUE THREAD

**Issue by ryanblock** [architect/aws-lite#15]
As requested by @andybee in the Arc / #aws-lite Discord, here's the Architect-centric list of plugins I'm looking at picking off on the way to 1.0. These assume, of course, that we're reasonably happy with the plugin API (see: https://github.com/architect/aws-lite/issues/14).

Moreover, this list doesn't intend to imply that other plugins folks intend to be published under `@aws-lite/*` won't be considered or accepted, just that these are the ones we, the maintainers, are likely ourselves to prioritize (namely because they help us migrate away before the Mar 2024 `aws-sdk` (v2) Lambda deprecation deadline).

Requirements:
- [ ] [API Gateway v2](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/resources.html) (`@architect/deploy`, `@architect/functions`)
- [x] [DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Types_Amazon_DynamoDB.html) (`@architect/functions`, `@architect/sandbox`)
- [ ] [SNS](https://docs.aws.amazon.com/sns/latest/api/API_Operations.html) (`@architect/functions`)
- [ ] [SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_Operations.html) (`@architect/functions`)
- [ ] [SSM](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Operations.html) (`@architect/functions`, `@architect/deploy`, `@architect/destroy`, `@architect/env`, `@architect/inventory`)
  - This will probably be a rare partial implementation to start, as Architect's usage is limited to the [Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html)

Nice to have:
- [ ] [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Operations.html) (`@architect/deploy`, `@architect/destroy`, `@architect/logs`)
- [ ] [CloudFront](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Operations.html) (`@architect/deploy`)
- [ ] [CloudWatch Logs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_Operations.html) (`@architect/destroy`, `@architect/logs`)
- [ ] [Lambda](https://docs.aws.amazon.com/lambda/latest/dg/API_Operations.html) (`@architect/deploy`)
- [ ] [S3](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html) (`@architect/asap`, `@architect/deploy`, `@architect/destroy`)
  - This one will likely need some outside help, it's chonky! 😅

**Comment by andybee** [comment]
Looks good, definitely focussing on the things Architect requires is a good v1 scope definition. I also don't necessarily dislike more being (clearly documented) partials that only tick the Architect dependency boxes to get a v1 out sooner...?

Are we considering any kind of "stake your claim" approach, to avoid 2x people attempting the same one?

**Comment by andybee** [comment]
I'm going to attempt the RDS Data API to dip my toe in as 1) it's small, 2) I have a direct requirement for it.
