### ISSUE TITLE
XML parsing / building

### ISSUE THREAD

**Issue by ryanblock** [architect/aws-lite#21]
As I've worked through some of the early plugins, it's becoming increasingly clear we can't get away with all these various AWS APIs returning unparsed XML strings. I'm already a bit annoyed that nearly half of our business logic's size (about 35KB of about 70KB) is dedicated only to vendoring utilities for marshalling and unmarshalling AWS-flavored JSON, so this stings. But we're building an AWS client here, and AWS uses a lot of XML, so them's the breaks.

I will be evaluating XML parsing / building solutions on:
- Hard requirement: no native bindings
- Whether it has dependencies (ideally none!), and whether it's actively maintained
- Time to require/import
- Footprint on disk
- Processing speed for parsing reasonably sized XML responses

I'll post results here once I've got them, a few solutions I'll be evaluating, in no particular order (and please do suggest more!):
- [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser)
- [xml](https://www.npmjs.com/package/xml)
- [xml-js](https://www.npmjs.com/package/xml-js)
- [xml2js](https://www.npmjs.com/package/xml2js)
- [xml2json](https://www.npmjs.com/package/xml2json)

**Comment by ryanblock** [comment]
Initial results:

## fast-xml-parser

- Initial install size: **197KB**
- Dependencies: 1
- Native bindings: no
- Bundle size (esbuild): **64KB**
- Require time (avg): 1.84 ms
- Require time (p95): 2 ms
- Require memory footprint (avg): 491.84 KB
- Require memory footprint (p95): 496 KB
- Parse performance (avg): 988 ops/sec
- Parse performance (p95): 986 ops/sec
- Parse memory footprint (avg): 9.96 MB
- Parse memory footprint (p95): 11.01 MB


## xml

> building only; ruled out so as not to have to bring in a second library

- Initial install size: **66KB**
- Dependencies: 0
- Native bindings: no
- Bundle size (esbuild): **8KB**
- Require time (avg): 1.22 ms
- Require time (p95): 2 ms
- Require memory footprint (avg): 288 KB
- Require memory footprint (p95): 288 KB


## xml-js

> Ruled out due to performance and highly verbose and complex output that required additional custom text parsing functions in order to make usable

- Initial install size: **561KB**
- Dependencies: 1
- Native bindings: no
- Bundle size (esbuild): **77KB**
- Require time (avg): 2.04 ms
- Require time (p95): 2 ms
- Require memory footprint (avg): 600.32 KB
- Require memory footprint (p95): 608 KB
- Parse performance (avg): 43 ops/sec
- Parse performance (p95): 40 ops/sec
- Parse memory footprint (avg): 8.89 MB
- Parse memory footprint (p95): 10.09 MB


## xml2js

> Got to benchmarking phase, but disqualified due to large module size, initial memory footprint, async/callbacky interface, and bizarre documentation

- Initial install size: **3.8MB**
- Dependencies: 2
- Native bindings: no
- Bundle size (esbuild): **217KB**
- Require time (avg): 4.28 ms
- Require time (p95): 5 ms
- Require memory footprint (avg): 1.37 MB
- Require memory footprint (p95): 1.40 MB


## xml2json

> Ahem

- Initial install size: **5.8MB**
- Dependencies: 10
- Native bindings: yes; disqualified
- Bundle size (esbuild): **285KB**

Looks like we'll be using fast-xml-parser, barring any unexpected issues!

**Comment by ryanblock** [comment]
@macdonst jinx!

**Comment by macdonst** [comment]
@ryanblock lolz, I thought you were replying to me. Good idea not checking what AWS used before digging in. Although, I take it as a good sign they use `fast-xml-parser`. One would think it can handle AWS XML.

**Comment by ryanblock** [comment]
Shipped in 0.8.0!
