### ISSUE TITLE
S3 HeadObject response should include ContentLength

### ISSUE THREAD

**Issue by metadaddy** [architect/aws-lite#56]
Currently, the response from `HeadObject` does not include `ContentLength`. For example,

```
{
  AcceptRanges: 'bytes',
  LastModified: 2023-12-11T21:00:23.000Z,
  ETag: 'f0b0de38617496a96511a3353781515e',
  VersionId: '4_z834de8717f3677488b980413_f40189138ebbcef16_d20231211_m210023_c004_v0402012_t0025_u01702328423101',
  ContentType: 'application/octet-stream'
}
```

`ContentLength` is in the response from S3, but it is ignored by `parseHeadersToResults`. The `HeadObject` API [Response Elements doc](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseElements) lists `Content-Length`, so it should be included.

[PR to closely follow]

**Comment by ryanblock** [comment]
Oh, I do so love how the `content-length` header is used contextually within the S3 API. 🫠

Thank you!
