### ISSUE TITLE
License field is missing on `@aws-lite/*-types` packages

### ISSUE THREAD

**Issue by just-boris** [architect/aws-lite#60]
### Describe the issue

The main package is licensed under Apache-2.0 license: https://github.com/architect/aws-lite/blob/6031039be3cfb2085ebc389a1a61453b30702f35/package.json#L34

As well as plugins, for example this one:

https://github.com/architect/aws-lite/blob/6031039be3cfb2085ebc389a1a61453b30702f35/plugins/apigateway/package.json#L17

However, the `*-types` packages do not have the license annotation: https://github.com/architect/aws-lite/blob/6031039be3cfb2085ebc389a1a61453b30702f35/plugins/apigateway/types/package.json

I guess, it is Apache-2.0, but it is not reflected in the npm metadata:

<img width="398" alt="image" src="https://github.com/architect/aws-lite/assets/812240/680a2794-74e4-4cfe-b022-ac9b6be468c1">

### Expected behavior

All packages have license information

### Steps to reproduce

n/a

### Platform / version

n/a

### How urgent do you feel this bug is?

In general, not sure, but missing license information does not allow using this package in projects with strict license linters.

**Comment by ryanblock** [comment]
@just-boris thanks for the heads up! Fixes for that will be out in a few minutes. 💕

**Comment by just-boris** [comment]
Thanks for a quick response!
