### ISSUE TITLE
RFC: compatibility with AWS SDK v2 / v3 client APIs

### ISSUE THREAD

**Issue by ryanblock** [architect/aws-lite#66]
We've heard folks requesting `aws-lite` compatibility with AWS SDK v2 and v3 client APIs ([example](https://twitter.com/samjarman/status/1729374653775520045)), which I wanted to discuss here in an RFC context. First, what that means in practice (with examples):

`aws-lite` client API:
```js
import awsLite from '@aws-lite/client'
const aws = await awsLite(options)
await aws.DynamoDB.GetItem(params)
```

`aws-sdk` v2 client API:
```js
import aws from 'aws-sdk'
const dynamo = new AWS.DynamoDB(options)
await dynamo.getItem(params).promise()
// legacy callback style
dynamo.getItem(params, callback)
```

`@aws-sdk/*` v3 client API:
```js
import { DynamoDBClient, GetItemCommand } from "@aws-sdk/client-dynamodb"
const client = new DynamoDBClient(options)
const command = new GetItemCommand(params)
await client.send(command)
```

So the thinking here would be that to ease the transition from SDK v2 or v3 to `aws-lite`, we should enable something that looks a bit like this:

```js
import awsLite from '@aws-lite/client'
const aws = await awsLite(options)

// v2-style async / await
await aws.DynamoDB.GetItem(params).promise() // Note the method casing!
// v2-style callback
aws.DynamoDB.GetItem(params, callback)

// v3-style
const client = new aws.DynamoDBClient(options)
const command = new aws.GetItemCommand(params)
await client.send(command)
```

### Current state of AWS SDK compatibility / commonality

As we implement various AWS service APIs, our general approach with aws-lite is to use AWS's method and property names (and their casing) in priority of: service API, AWS SDK v3, then SDK v2. However, these semantics may differ based on the various scenarios we see in method naming, request shapes, response shapes, and errors.

Errors are a bit out of scope for the topic at hand (especially as they differ wildly between SDKs v2 and v3), but I'll cover each of the others below.

#### Method names

Method names we generally follow the service API style, which is broadly Pascal-cased in AWS-land. For example, the S3 list objects v2 method is as follows:

- S3 API: `ListObjectsV2` ([reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html))
- SDK v3: `ListObjectsV2Command` ([reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/ListObjectsV2Command/))
- SDK v2: `listObjectsV2` ([reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property))

In this case, aws-lite uses `ListObjectsV2`.

#### Request shapes

aws-lite request shapes generally follow the service API style as well, which, as it happens, is usually is the same as what's found in AWS SDKs v2 and v3. For example, let's look at the main properties passed to S3's get object method:

- S3 API: `Bucket`, `Key`, etc. ([reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html))
- SDK v3: `Bucket`, `Key`, etc. ([reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/))
- SDK v2: `Bucket`, `Key`, etc. ([reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property))

Note: even though SDK v2 uses camel-cased `listObjectsV2`, it still Pascal-cases `Bucket` and `Key`.

Sometimes aws-lite uses different request properties when we've found a usability improvement that can be made. For example, some methods allow passing a boolean `pagination` (lowcased) property to enable recursive pagination of results – this is specific to aws-lite.

Another example is the addition of the `File` property in S3's put object method, allowing authors to specify a file on disk to be published to S3 instead of having to load a buffer themselves. This is not functionality found in the AWS SDKs.

#### Response shapes

aws-lite response shapes generally adhere to AWS SDK v3's interpolations and mutations. (Related: v3 generally hews quite close to v2 in my experience, so that's good.) We stick close to v3 specifically here in part to aid in interop moving into the future, in part to draft on v3's types (see more about [aws-lite types](https://aws-lite.org/using-typescript)), and in part because v3's changes are usually pretty sane – but not always. For example, let's look again at the response of S3's get object method:

- S3 API: file size in bytes is sent in the `Content-Length` header, while the object contents are sent in the http body ([reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html))
- SDK v3: file size in bytes is interpolated into the `ContentLength` property, while the object contents are a `Body` property, which is a [`StreamingBlobPayloadOutput`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-types/TypeAlias/StreamingBlobPayloadOutputTypes/) (something a lot of [folks really dislike](https://github.com/aws/aws-sdk-js-v3/issues/1877), [reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/))
- SDK v2: file size in bytes is interpolated into the `ContentLength` property, while the object contents are a `Body` property, which is a standard JS buffer

In this case aws-lite does the same `Content-Length` header to `ContentLength` property interpolation, while (currently) opting to pass through the `Body` property as a standard JS buffer (unless the object is JSON or XML, in which case it is automatically parsed). We opted to differ from v2 / 3 because that's what we thought the best user experience would be. SDKs are, ultimately, for humans.

### To shim or not to shim

So now we're at the crux of the discussion: do we shim v2 and/or v3 compatibility as in the example above, or not?

It wouldn't necessarily be hard to do; allow folks to opt into a `.promise()` method and some callback support (v2), or to append each method with `Command` to some redirected intermediate method (v3). But the work isn't done there for anyone who uses the shim.

Often, your migration will have gone smoothly, but not necessarily! Perhaps the method casing changed (as in `listObjectsV2` →`ListObjectsV2`). Or the request params or response shape may be slightly different (aws-lite provides a JS buffer body, SDK v3 provides a readable stream). Moreover, none of this accounts for the various irreconcilable differences in error shapes AWS made between v2 / 3; aws-lite does its best to bridge the two, but the responsible move will always be to run this new code in staging before shipping to production.

All this is to say: it would be irresponsible to assume aws-lite will flawlessly emulate SDK v2 and v3 semantics 100% of the time. The only responsible approach is to implement, then validate your changes.

Our guess is that when doing so you'll probably prefer working with aws-lite's much simpler client API. So while it may be straightforward to shimming the basic API semantics, I'd bring this back around and ask: given the above realities, is there meaningful value in shimming v2 / 3 client APIs for aws-lite?

**Comment by filmaj** [comment]
> is there meaningful value in shimming v2 / 3 client APIs for aws-lite?

My 2 cents: maybe once there's full API parity and most services are covered, there could be value in this via easier adoption. Until then, I don't think it should be a priority.

**Comment by andybee** [comment]
For me, I’ve seen this as a chance to revisit everywhere I use the AWS SDK v2 and rework it to the `awslite` way rather than v3 because care has been taken to follow an sensible path with naming and structure (e.g. the reasons above) which mostly fall to the API structure. Therefore I’d make more attempts at doubling down and promoting this that you should migrate to the lite way of doing things with a commitment to keep this SDK stable in the future, rather than… *gestures over there*

**Comment by ryanblock** [comment]
@andybee yeah, that's kind of how I've been approaching using it as well.

@filmaj I feel you on that.

Ok, going to close for now!
