### ISSUE TITLE
Support SSO

### ISSUE THREAD

**Issue by jolo-dev** [architect/aws-lite#76]
### Describe the problem underlying the enhancement request

My profiles are setup via `aws configure sso`.
So, I tried using `profile`

```ts
const aws = await awsLite({
  region: 'eu-central-1',
  profile: 'my-profile',
});
```

But I got `TypeError: Profile not found: my-profile`.

The profiles are stored in `~/.aws/config`

### Describe the solution you'd like (if any)

When entering a profile, it should determine the right profile regardless SSO or not.

### Describe alternative solutions you've considered

The AWS JS SDK v3 is able to detect that using the [@smithy/node-config-provider](https://github.com/smithy-lang/smithy-typescript/tree/main/packages/node-config-provider).

**Comment by ryanblock** [comment]
Shipped in 0.22!
