### ISSUE TITLE
add endpoint param

### ISSUE THREAD

**Issue by brianleroux** [architect/aws-lite#82]
### Describe the problem underlying the enhancement request

aws-sdk and @aws-sdk both support 'endpoint' so should we 

### Describe the solution you'd like (if any)

will mean parsing out protocol, host, port and endpointPrefix from 'endpoint' param

### Describe alternative solutions you've considered

living in a hollowed out log is sounding better day by day tbh

**Comment by metadaddy** [comment]
+1 on this - `endpoint` will make migrations from AWS SDK easier.

**Comment by ryanblock** [comment]
Stand by, coming very soon!
