### ISSUE TITLE
RFC: explicit plugin loading by default

### ISSUE THREAD

**Issue by ryanblock** [architect/aws-lite#96]
Early on in aws-lite I opted to pursue a path where, by default, we'd attempt to automatically load all available plugins. This was in large part due to the overwrought semantics of SDK v3, and wanting to provide a tool that, among other things, just works.

Under the hood, aws-lite makes a best-effort search for any installed `@aws-lite/*` or `aws-lite-plugin-*` modules in the most relevant possible node_modules dir the client is aware of. While this has largely been a simple and reliable way to use aws-lite, it has some drawbacks.

First, as we've seen, if your package manager doesn't properly flatten the dependency tree, [plugins may go missing](https://github.com/architect/aws-lite/issues/94) from the autoloader's search. While I think we've got that issue cornered, this approach also creates a specific challenge for Architect's Lambda dependency treeshaker:

Assume an Architect project generating Lambdas with the following root package.json file:

```json
{
  "dependencies": {
    "@aws-lite/client": "latest",
    "@aws-lite/dynamodb": "latest"
  }
}
```

Now assume the following Lambda handler:

```js
import awsLite from '@aws-lite/client'
export default async function handler () => {
  const aws = await awsLite()
  await aws.DynamoDB.GetItem({ params })
}
```

In the above example, aws-lite would successfully autoload the DynamoDB plugin when running locally, but Arc's treeshaker would not know that that handler needs `@aws-lite/dynamodb`, so the code would be broken in production.

It could be argued this is an Architect problem, per se, and not an aws-lite problem – but the above scenario would presumably be true if one bundled the handler code example.

So, while autoloading plugins is a nice and ergonomic way to get started with aws-lite, in production it may present significant issues that we may need to endeavor to resolve.

Assuming we make autoloading plugins an opt-in and not an opt-out, as things stand today there are a handful of potential implementation approaches we can take:

### 1. Register plugins via `import` / `require`

Upon import or require, each plugin proactively registers itself with `@aws-lite/client` behind the scenes:

```js
import awsLite from '@aws-lite/client'
import '@aws-lite/dynamodb' // DynamoDB is now registered with the client
const aws = await awsLite()
await aws.DynamoDB.GetItem({ params })
```

This approach could get a bit funky if you wanted to instantiate a second client with different credentials and different plugins, as operations in global scope that occur upon import would not re-run upon a second import. (In my prototyping, I couldn't get auto-registration working when running a second import statement, but perhaps there are ways to do that that I'm not currently aware of.) Example:

```js
import awsLite from '@aws-lite/client'

// First client
import '@aws-lite/dynamodb' // DynamoDB is now registered with the first client
import '@aws-lite/lambda' // Lambda is now registered with the first client
const clientOne = await awsLite({ credentials: $foo })

// Second client
import '@aws-lite/dynamodb' // Depending on implementation: either nothing is registered with the second client, or both DynamoDB and Lambda are registered; neither scenario is desired
const clientTwo = await awsLite({ credentials: $bar })
```

### 2. Pass imported plugins

Pretty explicit, traditional, and verbose – probably not very surprising, either:

```js
import awsLite from '@aws-lite/client'
import dynamodb from '@aws-lite/dynamodb'
const aws = await awsLite({ plugins: [ dynamodb ] })
await aws.DynamoDB.GetItem({ params })
```

And if you want a second client with a second set of plugins, just pass them along:

```js
import awsLite from '@aws-lite/client'
import dynamodb from '@aws-lite/dynamodb'
import lambda from '@aws-lite/lambda'

const clientOne = await awsLite({ plugins: [ dynamodb ] })
const clientTwo = await awsLite({ plugins: [ dynamodb, lambda ] })
```

### 3. Pass strings

How the `plugins` param currently works! It's nice and light, but sadly it doesn't work well with Lambda treeshaking, so I'm probably willing to eliminate it on that basis alone. Presented here just to cover the example:

```js
import awsLite from '@aws-lite/client'
const aws = await awsLite({ plugins: [ '@aws-lite/dynamodb' ] })
```

---

If you have ideas for other approaches, please let me know – otherwise, looking forward to your thoughts and feedback!

**Comment by brianleroux** [comment]
my $0.02 is we should recommend and demonstrate option #2 … least surprise is hugely important but also keeps dynamic loading bugs at bay.

**Comment by tbeseda** [comment]
I like **#2** best.

Maybe invert the autoLoad option to default to false, but keep it around?

**Comment by ryanblock** [comment]
Def @tbeseda, imo it's feeling like a bit of a fait accompli that we're going to have to change the autoload default from true to false here. While I really like the autoloading feature, and it feels worth keeping around, perhaps it's also setting folks up for bugs. I'm not sure.

Anyhow, my chief hesitation with the `Pass imported plugins` approach is that it gets so verbose and just feels really noisy. We could also accept raw, fulfilled or unfulfilled `import` promises to help make it more minimal:

```js
// valid
import dynamodb from '@aws-lite/dynamodb'
import lambda from '@aws-lite/lambda'
await awsLite({ plugins: [ dynamodb, lambda ] })

// also valid
await awsLite({ plugins: [ import('@aws-lite/dynamodb'), import('@aws-lite/lambda') ] })

// also valid
await awsLite({ plugins: [ await import('@aws-lite/dynamodb'), await import('@aws-lite/lambda') ] })

// no longer accepted
await awsLite({ plugins: [ '@aws-lite/dynamodb', '@aws-lite/lambda' ] })
```

**Comment by taphill** [comment]
My completely unsolicited opinion would also be for option 2!

This is relevant to me as someone brand new to aws-lite because I got stuck for about 10/15 min trying to get this basic example working:

```javascript
import awsLite from "@aws-lite/client";
const aws = await awsLite({ region: "us-east-1" });

await aws.S3.CreateBucket({
  Bucket: "my-bucket",
});
```

My issue was that, by looking at the example code in the docs, I didn't realize I was required to also npm install the `@aws-lite/s3` package

Basically I just clicked the "Make your first [aws-lite call in 60 seconds](https://aws-lite.org/#install-aws-lite)" link, copy pasted the example and installed the `@aws-lite/client`.

I acknowledge that I should've done a better job actually reading the docs, but if plugins had to be explicitly imported I would've know I needed that package immediately just by looking at the code.

**Comment by taphill** [comment]
Also, I'm really excited about this project, so I wanted to say thanks y'all! :smile:

**Comment by andybee** [comment]
I agree with most (everyone?) that Option 2 passing the imports is the way to go. Should probably remove the ability to pass a string name of an import to avoid potential bugs (add a warning if you do it so it migrates predictably?) and make "auto import" disabled by default with suitable warnings in the documentation about why it might be a BAD THING(R)(TM) (but not remove it entirely because for some people it might be quite neat and not trip them up?)

Definitely think @taphill's point on not being easy to read in a getting started context is a strong reason to push ahead with this, too. The boring/verbose/obvious/easy to read option is nearly always the right one! 😉

**Comment by taphill** [comment]
I don't know if this would make any sense in the context of this project, but javascript devs (for better or worse) would find a root level config file very unsurprising. Would autoloading still be able to work with something like this?

```javascript
// awsLite.config.js

import { config } from '@aws-lite/client'
import dynamodb from '@aws-lite/dynamodb'
import lambda from '@aws-lite/lambda'

export default config({
  plugins: [ dynamodb, lambda ],
});
```

**Comment by ryanblock** [comment]
@taphill your (and everyone's) opinion is entirely solicited! Your example of how our example fell over for you really seals the deal for me on this change. I'll probably wrap it up and roll it out later today as 0.17.0 (which npm will treat as a breaking change since it's major version 0).

Regarding a config file: I'm not sure. It would work, but unless that config path were explicitly passed, we'd be in roughly the same boat of the client searching the filesystem for a config file. I'm not necessarily opposed to having a client config file, but I'd like to bucket that as a separate scope of work, as its motivations and considerations differ from this matter of explicit plugin loading.

@andybee I'm completely removing the string-passing approach – we're still pre-1.0 (intentionally!), so this is the kind of change I feel comfortable making right now while things are still settling in. (Were it a future post-1.0 version I'd definitely keep to our general approach of always having a backward compatible path wherever possible.)
