### ISSUE TITLE
"Package" is reserved word

### ISSUE THREAD

**Issue by jarimustonen** [architect/aws-lite#99]
### Describe the issue

I'm trying to get my first application up and running, so please excuse me if the bug report is misplaced. Anyhow, I get the following error:

```
node_modules/@aws-lite/client/src/get-plugins.js:66:10: ERROR: "package" is a reserved word and cannot be used with the "esm" output format due to strict mode [plugin css-bundle-plugin]
```

Here's how I got to this point:

1. I installed Remix Grunge template: `npx create-remix@latest --template remix-run/grunge-stack`
2. Bumped all the versions in the package.json to latest. Out of all the software installed, I think these versions might be of importance: `@architect/architect` to `11.0.3` and `@architect/functions` to `8.0.2`.
3. run `npm install && npm run dev`
4. The error appeared
5. Made sure that the latest version is used by running: `npm install @aws-lite/client --save-exact`. It installed version `0.17.1`.

### Expected behavior

No error.

### Steps to reproduce

Please see the description.

### Platform / version

- OS + version: macOS 14.2.1
- Node version: 21.5
- Package manager version: npm 10.2.4
- @aws-lite/client: 0.17.1

### How urgent do you feel this bug is?

None

**Comment by ryanblock** [comment]
Should be patched in v0.17.2, thank you!
